---
- name: Check if cluster is already initialized
  stat:
    path: "{{ kubernetes_admin_config }}"
  register: kubernetes_cluster_info

- name: Check kubernetes cluester status
  set_fact: kubernetes_cluster_init=true
  when: kubernetes_cluster_info.stat.exists

- name: Check kubernetes cluester status
  set_fact: kubernetes_cluster_init=false
  when: not kubernetes_cluster_info.stat.exists

- name: Generating Token
  command: kubeadm token generate
  when: not kubernetes_cluster_init
  register: kubernetes_token

- name: Setting Token On Master
  set_fact: kubernetes_token="{{kubernetes_token.stdout}}"

#
# - name: init_cluster | Setting Token On Non-Master(s)
#   set_fact:
#     k8s_token: "{{ hostvars[k8s_master]['k8s_token'] }}"
#   no_log: true
#   when: >
#         (inventory_hostname != k8s_master) and
#         not k8s_cluster_init

- name: Initializing kubernetes cluster
  become: true
  command: >
           kubeadm init \
           --pod-network-cidr=10.244.0.0/16  \
           --apiserver-advertise-address=kube-master \
           --token {{ kubernetes_token }}
  when: not kubernetes_cluster_init
